version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g typescript
      - npm install -g tslint
      - npm install -g ts-node
      - npm install -g tsconfig-paths
      - cd backend && npm install && cd ..
  build:
    commands:
      - cd backend && npm run build && cd ..
artifacts:
  files:
    - package.json
    - package-lock.json
    - 'dist/**/*'
  base-directory: ./backend
