version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g typescript
      - cd backend && npm install && cd ..
  build:
    commands:
      - cd backend && npm run build && cd ..
  post_build:
    commands:
      - mv ./backend/dist ./dist
artifacts:
  files:
    - package.json
    - package-lock.json
    - 'dist/**/*'
  base-directory: ./backend
